import Head from "next/head";
import styles from "@/styles/Home.module.css";


export default function Home() {
	const handleClick = () => {
		// update
		// fetch('/api/update_product?id=5bea39cb-58ac-4ca9-b98a-5371afbbdf6a&name=Arroz&unit=g&x1000=kg', { method: 'PUT' })
		// 	.then(res => res.json())
		// 	.then(console.log);

		// delete
		// fetch('/api/delete_product?id=8492cac7-3f1c-42a1-b156-df9159bb20d3', { method: 'DELETE' })
		// 	.then(res => res.json())
		// 	.then(console.log);

		// add
		// fetch('/api/add_product?name=Feijão Carioquinha&unit=g&x1000=kg', { method: 'POST' })
		// 	.then(res => res.json())
		// 	.then(console.log);

		// get
		// fetch('/api/products')
		// 	.then(res => res.json())
		// 	.then(console.log);
	}

	return (
		<>
			<Head>
				<title>Bairral: Logística da Cozinha</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<button onClick={handleClick}>fetch</button>
			</div>
		</>
	);
}
